// `android/` is generated by `expo prebuild`, so anything edited there by hand
// is gone the next time it runs — including the release signing config. This
// plugin re-applies it on every prebuild instead.
//
// Expo's template signs release builds with the *debug* keystore. That APK
// installs fine, but every rebuild must be signed by the same key or Android
// rejects the upgrade, so shipping the shared debug key would strand the
// cashiers' installs. The real key lives in android/keystore.properties, which
// is gitignored — the repo describes how to sign, never the secret itself.
const { withAppBuildGradle } = require('@expo/config-plugins')

const LOADER = `
def pcaKeystoreProps = new Properties()
def pcaKeystoreFile = rootProject.file("keystore.properties")
if (pcaKeystoreFile.exists()) {
    pcaKeystoreFile.withInputStream { pcaKeystoreProps.load(it) }
}
`

const RELEASE_SIGNING = `        release {
            // Falls back to the debug key when keystore.properties is absent,
            // so a fresh clone still builds; a real release needs the file.
            if (pcaKeystoreProps.getProperty('PCA_UPLOAD_STORE_FILE')) {
                storeFile file(pcaKeystoreProps.getProperty('PCA_UPLOAD_STORE_FILE'))
                storePassword pcaKeystoreProps.getProperty('PCA_UPLOAD_STORE_PASSWORD')
                keyAlias pcaKeystoreProps.getProperty('PCA_UPLOAD_KEY_ALIAS')
                keyPassword pcaKeystoreProps.getProperty('PCA_UPLOAD_KEY_PASSWORD')
            } else {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
    }`

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents

    if (gradle.includes('PCA_UPLOAD_STORE_FILE')) {
      return cfg
    }

    // Load the properties before the `android { }` block that reads them.
    gradle = gradle.replace(/^android \{/m, `${LOADER.trim()}\n\nandroid {`)

    // Add a `release` entry beside the template's `debug` signing config.
    gradle = gradle.replace(
      /(signingConfigs \{\s*\n\s*debug \{[\s\S]*?\n {8}\}\n)( {4}\})/m,
      `$1${RELEASE_SIGNING}`,
    )

    // Point the release build type at it instead of the debug key.
    gradle = gradle.replace(
      /(buildTypes \{[\s\S]*?release \{[\s\S]*?)signingConfig signingConfigs\.debug/m,
      '$1signingConfig signingConfigs.release',
    )

    cfg.modResults.contents = gradle
    return cfg
  })
}
